### PR TITLE
Improve counsel-projectile-find-file performance

### PR DESCRIPTION
**Pull request by ambihelical**
Current code will show significant lag for projects with large numbers
of files.  Tests with 400K files shows 15-20s lag for
counsel-projectile-find-file.  Profiling showed that this was
due to the preprocessing of projectile-current-project-files to add
'ivy-virtual face to files not already in a buffer.  To fix this,
a display transformer was added for this command so that the face
modification was applied only to at most ivy-height files.

The preprocessed file list was also used by counsel-projectile
code paths, so some additional modifications were made to ensure
that that code path does not change behavior.  Any similar issues in
counsel-projectile performance was not addressed in this commit.

Details:

* move 'ivy-virtual face change to a display transformer function
* use projectile-current-project-files instead of counsel-projectile--file-list
  for ivy-read.
* reduce the scope of counsel-projectile--file-list, making it return
  only unvisited files, and renaming it accordingly.  This is now only
  used indirectly by the counsel-projectile function.
* change ivy-switch-buffer-transformer to propertize files at display time.

### CODE REVIEW

**Comment by ambihelical** [comment]
This should fix #31 and #41.

**Comment by ericdanan** [comment]
Thanks a lot, commit merged, this is clearly more efficient.

I also did some time measurement with [this macro](http://lists.gnu.org/archive/html/help-gnu-emacs/2008-06/msg00087.html) on a directory containing 400K empty files that I generated for this purpose. I did also observe that `counsel-projectile-find-file` was slower than `projectile-find-file`, although the difference was not as large as for you: ~20s vs ~15s, so 5s lag (perhaps having no subdirectories nor ignored files plays a role...). After your commit `counsel-projectile-find-file` is down to ~15s as well. On the other hand, `counsel-projectile` takes ~19s, so there is perhaps room for improvement here, I will think about it.

**Comment by ambihelical** [comment]
Interesting that you didn't see the same magnitude of improvement.  Are you possibly not using projectile caching?

**Comment by ericdanan** [comment]
Yes, I have `projectile-enable-caching` set to `nil`. Setting it to `t` and once the project is cached, `projectile-find-file` is down to 0.5s. `counsel-projectile-find-file` takes 4.5s before your commit and also down to 0.5s afterwards. `counsel-projectile` takes 5.5s before and 3s after, will have to do something to make it faster.

**Comment by ericdanan** [comment]
FYI, I improved `counsel-projectile` speed. I think it should now be about as responsive as `counsel-projectile-find-file` except if you have a lot of open buffers. I didn't test with 400K files though.

**Pull request closed without merging**
